sudo: false
language: python
matrix:
  include:
  - env: TEST='py.test'
    python: '2.7'
    install:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest-flake8 pytest-cov
    script: py.test --flake8 --cov=travisci
  - env: TEST='py.test'
    python: '3.5'
    install:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest-flake8 pytest-cov    
    script: py.test --flake8 --cov=travisci
env:
  global:
    - secure: "Cvr0rFAI2P3HaLsFy2jBl/iUzkgDKOiZPFdy8u6ymNRI4GqLFe9BFEP7/kgo4B0fvOdh5HI6FiY12WvBFPuBHsrTHygULBW8EqnuRxCqyJ0L3MeNzeZQ2MShEwjatsJ+mIGLV6AsmgT7cqBYSYxMOH71/3icDgZaHOEk1+L1QS48Ii1qnzwW9j1/dmcfGC0jSOzmj9hIqEqQiY2TGaiVrRw51/JfYExyod76n9C+70ZrPOeuGHDjP+g9Pt0/OhLkblDcxDyTxGUqFpS2yemNrO56JDKAWkqL40aFgfpCR6Zkl/BnmYgSN0Svl6h/XAv7TfzD8+1rmGSWjUmvGr7S+qoxQBg1Jup8AvKX9ljegb9in/GFT/66ucZ0EJsfb9GNRwRbaahxOPcfVtiCg8XKtHCQWG63vsanNw1G08LqdSOtLR4j9KHqFdBVfok0Zz2Lve+73F8nwOE2VcCCRKA0kaxohgVUKxshbMyvbpEDDlulCgCS3aWZwgXMAH4Hn9SdGXxO7jbEQTNmaS46tVLvUZeL9VNftO1xwncJftyDElBflr7UbgMfo5WgAR9sKrLNBgy+WxGSOWnF6cOatgyQAlbnJYgpwFWZ9Plm02FXmjgA8NcYiTJrXXBOiL977HR6P0CO87tGrJzlDgg/yapkTmCIZO5/Yauz3wNeeIxaTk8="

